/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminBlockedDatesRouteImport } from './routes/admin/blocked-dates'
import { Route as AdminBusinessHoursRouteImport } from './routes/admin/business-hours'
import { Route as AdminClinicSettingsRouteImport } from './routes/admin/clinic-settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminWebsiteContentRouteImport } from './routes/admin/website-content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlockedDatesRoute = AdminBlockedDatesRouteImport.update({
  id: '/admin/blocked-dates',
  path: '/admin/blocked-dates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessHoursRoute = AdminBusinessHoursRouteImport.update({
  id: '/admin/business-hours',
  path: '/admin/business-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClinicSettingsRoute = AdminClinicSettingsRouteImport.update({
  id: '/admin/clinic-settings',
  path: '/admin/clinic-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteContentRoute = AdminWebsiteContentRouteImport.update({
  id: '/admin/website-content',
  path: '/admin/website-content',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/results': typeof ResultsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blocked-dates': typeof AdminBlockedDatesRoute
  '/admin/business-hours': typeof AdminBusinessHoursRoute
  '/admin/clinic-settings': typeof AdminClinicSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/website-content': typeof AdminWebsiteContentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/results': typeof ResultsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blocked-dates': typeof AdminBlockedDatesRoute
  '/admin/business-hours': typeof AdminBusinessHoursRoute
  '/admin/clinic-settings': typeof AdminClinicSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/website-content': typeof AdminWebsiteContentRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/results': typeof ResultsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blocked-dates': typeof AdminBlockedDatesRoute
  '/admin/business-hours': typeof AdminBusinessHoursRoute
  '/admin/clinic-settings': typeof AdminClinicSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/website-content': typeof AdminWebsiteContentRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/results'
    | '/reviews'
    | '/services'
    | '/admin/appointments'
    | '/admin/blocked-dates'
    | '/admin/business-hours'
    | '/admin/clinic-settings'
    | '/admin/login'
    | '/admin/services'
    | '/admin/website-content'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/results'
    | '/reviews'
    | '/services'
    | '/admin/appointments'
    | '/admin/blocked-dates'
    | '/admin/business-hours'
    | '/admin/clinic-settings'
    | '/admin/login'
    | '/admin/services'
    | '/admin/website-content'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/results'
    | '/reviews'
    | '/services'
    | '/admin/appointments'
    | '/admin/blocked-dates'
    | '/admin/business-hours'
    | '/admin/clinic-settings'
    | '/admin/login'
    | '/admin/services'
    | '/admin/website-content'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  ResultsRoute: typeof ResultsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBlockedDatesRoute: typeof AdminBlockedDatesRoute
  AdminBusinessHoursRoute: typeof AdminBusinessHoursRoute
  AdminClinicSettingsRoute: typeof AdminClinicSettingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminWebsiteContentRoute: typeof AdminWebsiteContentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blocked-dates': {
      id: '/admin/blocked-dates'
      path: '/admin/blocked-dates'
      fullPath: '/admin/blocked-dates'
      preLoaderRoute: typeof AdminBlockedDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/business-hours': {
      id: '/admin/business-hours'
      path: '/admin/business-hours'
      fullPath: '/admin/business-hours'
      preLoaderRoute: typeof AdminBusinessHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clinic-settings': {
      id: '/admin/clinic-settings'
      path: '/admin/clinic-settings'
      fullPath: '/admin/clinic-settings'
      preLoaderRoute: typeof AdminClinicSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website-content': {
      id: '/admin/website-content'
      path: '/admin/website-content'
      fullPath: '/admin/website-content'
      preLoaderRoute: typeof AdminWebsiteContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  ResultsRoute: ResultsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBlockedDatesRoute: AdminBlockedDatesRoute,
  AdminBusinessHoursRoute: AdminBusinessHoursRoute,
  AdminClinicSettingsRoute: AdminClinicSettingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminWebsiteContentRoute: AdminWebsiteContentRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
